route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'ses'
receivers:
  - name: 'ses'
    email_configs:
    - smarthost: 'email-smtp.us-east-1.amazonaws.com:587'
      auth_username: 'AKIAUSW45M2WLWUJ24GB'
      auth_password: "BCa2C3WeJt+K0PLvGP1Ca94PCPGDH2kTVs68mYFkntDd"
      from: 'joindevops@gmail.com'
      to: 'info@joindevops.com'
      headers:
        subject: 'Prometheus Mail Alerts'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
